# Base Image
FROM guacamole/guacamole

# Create dir app
RUN mkdir /app

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Updates and Package Installations
RUN apt update && apt upgrade -y

RUN DEBIAN_FRONTEND=noninteractivate ap-get install -y --no-install-recommends \
     libness-ldap \
     libpam-ldap \
     ldap-utils \
     nscd

# Testing tools
# RUN apt install -y nano rsync nmap ssh rsync net-tools

# Start command
# ENTRYPOING ["bash"]

