version: '2.0'

# networks
# create a network 'guacnetwork_compose' in mode 'bridged'
networks:
  guacnetwork:
    driver: bridge

# services
services:
  # guacd
  guacd:
    container_name: guacd
    image: guacamole/guacd
    networks:
      guacnetwork:
    restart: always
    volumes:
    - ./drive:/drive:rw
    - ./record:/record:rw
  # postgres
  postgres:
    container_name: postgres
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: guacamole_password
      POSTGRES_USER: guacamole_user
    image: postgres
    networks:
      guacnetwork:
    restart: always
    volumes:
    - ./init:/docker-entrypoint-initdb.d:ro
    - ./data:/var/lib/postgresql/data:rw

  # guacamole
  guacamole:
    container_name: guacamole
    depends_on:
    - guacd
    - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: guacamole_password
      POSTGRES_USER: guacamole_user
      GUACAMOLE_HOME: /etc/guacamole
      # LDAP_HOSTNAME: 192.168.1.1
      # LDAP_ENCRYPTION_METHOD: none
      # LDAP_USER_BASE_DN: ou=people,dc=field,dc=example,dc=com
      # LDAP_CONFIG_BASE_DN: ou=computer,dc=field,dc=example,dc=com
      # LDAP_GROUP_BASE_DN: ou=group,dc=field,dc=example,dc=com
      # LDAP_USERNAME_ATTRIBUTE: uid
      # LDAP_GROUP_NAME_ATTRIBUTE: cn
    build:
      context: ./Dockerfiles/.
      dockerfile: dockerfile_guacamole_ldap
    # image: guacamole/guacamole
    volumes:
    - ./guacamole_home:/etc/guacamole
    - ./ldap/libnss-ldap.conf:/etc/libnss-ldap.conf
    - ./ldap/nsswitch.conf:/etc/nsswitch.conf
    - ./ldap/pam_ldap.conf:/etc/pam_ldap.conf
    links:
    - guacd
    networks:
      guacnetwork:
    ports:
    - 8080/tcp
    restart: always

  #nginx proxy
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./nginx/mysite.template:/etc/nginx/conf.d/mysite.template
    - /etc/pki/tls/certs/nginx:/etc/nginx/ssl
    ports:
    - 443:443
    links:
    - guacamole
    networks:
      guacnetwork:

    command: /bin/bash -c "apt-get -y update && apt-get -y install openssl && openssl req -days 3650 -nodes -newkey rsa:2048 -new -x509 -keyout /etc/nginx/ssl/self-ssl.key -out /etc/nginx/ssl/self.cert -subj '/C=US/ST=California/L=San Diego/O=some name/OU=IT/CN=yourdomain.com' && cp -f -s /etc/nginx/conf.d/mysite.template /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

